### ISSUE TITLE
Some dbc do not have blank line between SG_ record and next BO_ record

### ISSUE THREAD

**Issue by jamespr615** [downtimes/can-dbcparser#2]
Truly brillant work.   Clean. Light. Economical.

I noticed some automotive dbc do not have blank line between SG_ record and next BO_ record. 
To simulate - take your reference dbc and remove the blank lines between last SG_ record and next BO_ record. 

I tried this in signal.cpp and it seemed OK. 

std::istream& operator>>(std::istream& in, Signal& sig) {

/*** looking for  the next message  **/ 
    int c = in.peek();
    if ('B' == c) {  
        in.setstate(std::ios_base::failbit);
        return in;
    }
    std::string line;
    std::getline(in, line);
    if (!line.empty() && *line.rbegin() == '\r') line.erase(line.length() - 1, 1);
    if (line.empty()) {
        in.setstate(std::ios_base::failbit);
        return in;
    }

**Comment by downtimes** [comment]
Thanks for your kind words.

Since I was moving I couldn't respond in the last few weeks.
I applied your improvements to the code.
